name: Update README with GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # Chạy mỗi ngày một lần
  workflow_dispatch: # Cho phép chạy tay nếu cần

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        env:
          GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          curl -o github-stats.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=CHT7&theme=dracula&hide_border=true&include_all_commits=true&count_private=true&layout=compact&token=$GH_TOKEN"

      - name: Update README
        run: |
          sed -i '/<!--START_SECTION:stats-->/, /<!--END_SECTION:stats-->/c\
          <!--START_SECTION:stats-->\n\
          ![](./github-stats.svg)\n\
          <!--END_SECTION:stats-->' README.md

      - name: Commit & Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add README.md github-stats.svg
          git commit -m "Updated GitHub Stats" || echo "No changes to commit"
          git push
