name: Update README with GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # Chạy mỗi ngày một lần
  workflow_dispatch: # Cho phép chạy tay nếu cần

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update README
        env:
          GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          curl -o README.md "https://github-readme-stats.vercel.app/api/top-langs/?username=CHT7&theme=dracula&hide_border=true&include_all_commits=true&count_private=true&layout=compact&token=$GH_TOKEN"

      - name: Commit & Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated GitHub Stats"
          git push
